<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task.proto

namespace GPBMetadata;

class Task
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0adc010a0a7461736b2e70726f746f120570726f746f22270a0752657175657374120a0a02696418012001280912100a086578656354696d6518022001280322340a08526573706f6e7365120a0a026964180120012809120e0a06737461747573180220012809120c0a04636f646518032001280332600a045461736b122b0a06437265617465120e2e70726f746f2e526571756573741a0f2e70726f746f2e526573706f6e73652200122b0a0644656c657465120e2e70726f746f2e526571756573741a0f2e70726f746f2e526573706f6e73652200620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

