doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            DeferredTask:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/DomainService/TasksDeferredService/Entity'
                prefix: 'App\DomainService\TasksDeferredService\Entity'
                alias: DeferredTask
            Push:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Domain/Push/Entity'
                prefix: 'App\Domain\Push\Entity'
                alias: Push
