version: '3.8'

services:
  php-fpm:
    build:
      context: ./docker/php-fpm/
      dockerfile: Dockerfile
    networks:
      - my-network
    ports:
      - "9000:9000"
    volumes:
      - ./:/app
      - ./docker/php-fpm/dev/php.ini:/usr/local/etc/php/php.ini
    working_dir: /app
    container_name: 'php-fpm'
    depends_on:
      - mysql

  nginx:
    image: nginx:1.15.0
    container_name: 'nginx'
    working_dir: /app
    networks:
      - my-network
    ports:
      - '8080:80'
    volumes:
      - ./:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf

  mysql:
    image: mysql:8.0
    restart: always
    container_name: 'mysql'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    working_dir: /app
    volumes:
      - ./docker/data/dump/mysql:/app/dump
      - ./docker/data/mysql:/var/lib/mysql

networks:
  my-network:

